# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47d389b1681b7b1d4eb13e51ea74a66465aaa24cdadef97e22c0a57aa260a3130862def59bbffa45d267f642397c8dae107a47113c81f53bca80e3d8897aca87

test:
  secret_key_base: da0d328d9a61f79398a374d192aa51eeb3057815adcc282b6fb97eb919976c7759a2dc574fc69b74cedfd4562e0b49d5d75b1f84a731aa264c119fdfcb6d864a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
